CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS __migrations (
    id BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    checksum TEXT NOT NULL,
    ran_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
